export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';
export const CREATE_LISTING = 'CREATE_LISTING';
export const FETCH_LISTINGS = 'FETCH_LISTINGS';
export const FETCH_LISTING = 'FETCH_LISTING';
export const DELETE_LISTING = 'DELETE_LISTING';
export const EDIT_LISTING = 'EDIT_LISTING';

export const CREATE_COMPANY = 'CREATE_COMPANY';
export const FETCH_COMPANIES = 'FETCH_COMPANIES';
export const FETCH_COMPANY = 'FETCH_COMPANY';
export const DELETE_COMPANY = 'DELETE_COMPANY';
export const EDIT_COMPANY = 'EDIT_COMPANY';